version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-18.04-hdf5-1.10.4
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-18.04-hdf5-1.10.7
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-18.04-hdf5-1.10.8
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-20.04-hdf5-1.12.0
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-20.04-hdf5-1.13.0-mpich-3.4.3
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-20.04-hdf5-1.13.0
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-20.04-hdf5-1.14.0
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/ubuntu-20.04-hdf5-1.14.1
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily
