name: clang-format Check
on: 
  workflow_dispatch:
  push:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Run clang-format style check for C programs.
      uses: DoozyX/clang-format-lint-action@84b814a54950e27ac65a62069802df099405ef77 # v0.11
      with:
        source: '.'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 10
        inplace: True
        style: file
        # exclude: './config '
    - uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02 # v7.5.0
      with:
          author_name: github-actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Committing clang-format changes'
